### ISSUE TITLE
Problem run project

### ISSUE THREAD

**Issue by BrunoFord** [liamwb/ArbitrageBetting2#1]
Hello, first thanks for the project
I'm trying to run it and I'm having some problems, since there's no guide. Can someone give a help?
Thanks

**Comment by liamwb** [comment]
You'll probably have more luck with ArbitrageBetting3 (https://github.com/liamwb/ArbitrageBetting3), I took a different approach and it went much better. You'll have to get an API key for TheOdds API in order to run the script. Good luck, and if you have more questions I'm happy to try and help, but really these projects are just to help me learn -- I'm not an expert by any means.
